name: CI/CD Pipeline

on:
  push:
    branches: frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: cd Frontend/jjinppang-fe && yarn install --frozen-lockfile
      
    - name: Build
      run: cd Frontend/jjinppang-fe && yarn build
      
  deploy:
     needs : build-and-test 
     runs-on : ubuntu-latest 

     steps :
     - uses : actions/checkout@v2
     
     - name : Build and Deploy 
       uses : JamesIves/github-pages-deploy-action@4.1.5 
       with :
         GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
         BRANCH : gh-pages # The branch the action should deploy to.
         FOLDER : Frontend/jjinppang-fe/build # The folder the action should deploy.
         CLEAN : true # Automatically remove deleted files from the commit.
